### ISSUE TITLE
Kinda works on AK500 Digital

### ISSUE THREAD

**Issue by Its-Juice** [raghulkrishna/deepcool-ak620-digital-linux#5]
Hi. I have followed every instruction (probably idk). The cpu usage works and displays accurate usage (probably). Temperature doesn't work tho. Any help?

**Comment by hykelvinlee42** [comment]
You need to figure out the temperature sensors available by running the following Python code and pick the one you want to use for display.

```python
import psutil
print(psutil.sensors_temperatures().keys())
```

Details in my [forked repo](https://github.com/hykelvinlee42/deepcool-ak-series-digital-linux).

**Comment by Its-Juice** [comment]
> You need to figure out the temperature sensors available by running the following Python code and pick the one you want to use for display.
> 
> ```python
> import psutil
> print(psutil.sensors_temperatures().keys())
> ```
> 
> Details in my [forked repo](https://github.com/hykelvinlee42/deepcool-ak-series-digital-linux).

Nope, managed to get my cpu sensor (coretemp probably) and used the script as the instructions said. Still displaying 0 degrees.

**Comment by Its-Juice** [comment]
> Were you able to see the temperature from the console?
> 
> ```python
> print(psutil.sensors_temperatures()['coretemp'][0].current)  # assume you're using using coretemp
> ```
> 
> If it's showing 0 degree, then perhaps it's `psutil` not able to read from your system. Also check [line 55 of `deepcool-ak620-digital.py`](https://github.com/raghulkrishna/deepcool-ak620-digital-linux/blob/main/deepcool-ak620-digital.py#L55), see if it's using coretemp instead of nct6687.
 
Yep this fixed it. Now the issue is that it doesn't automatically start on boot.

**Comment by raghulkrishna** [comment]
can you try using the latest version?

**Comment by Its-Juice** [comment]
> can you try using the latest version?

Yes i started using the latest version and it now works perfectly. Great job on your behalf! (Issue fixed)
